# This tool converts the expected/run table that Codingbat.com
# gives you once youve solved a problem, into a series of
# assert statements in python

print("# The following code was generated by the expected_to_assert program")
f = open("expected_input_warmup1.dat","r")
for line in f:
    print("assert",line.split("\t")[0].replace("→","=="))
f.close()
print()
print("print('all tests passed successfully')")